name: Deploy Docker React
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t urvish91/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true urvish91/docker-react npm run test